CREATE TABLE Users (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Username varchar(20) NOT NULL UNIQUE,
  Type ENUM('Admin','Normal') NOT NULL DEFAULT 'Normal'
);

CREATE TABLE Categories (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE Articles (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  User_Id INT NOT NULL,
  Category_Id INT NOT NULL,
  Write_Up TEXT NOT NULL,

  FOREIGN KEY fk_user(User_Id)
  REFERENCES Users(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,

  FOREIGN KEY fk_category(Category_Id)
  REFERENCES Categories(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE Comments (
  Id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Article_Id INT NOT NULL,
  User_Id INT NOT NULL,
  Comment TEXT NOT NULL,

  FOREIGN KEY fk_user(User_Id)
  REFERENCES Users(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,

  FOREIGN KEY fk_article(Article_Id)
  REFERENCES Articles(Id)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);